FROM tensorflow/tensorflow:2.0.0-gpu-py3

# Install system packages
RUN apt-get update && apt-get install -y --no-install-recommends \
      bzip2 \
      g++ \
      git \
      graphviz \
      libgl1-mesa-glx \
      libhdf5-dev \
      openmpi-bin \
      wget && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /workspace
COPY src/requirements.txt /workspace/requirements.txt

RUN pip install -r requirements.txt

ENV PYTHONPATH='/src/:$PYTHONPATH'
